#server configuration
server:
    port: ${PORT}
    #error:
        #include-stacktrace: never

#spring configuration
spring:
    profiles:
        active: ${PROFILE}

    application:
        name: Mercatto

#Open api swagger ui 
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        persist-authorization: true

#prefix endpoints configuration
api:
    prefix: ${PREFIX} 

#secret jwt
jwt:
    secret: ${SECRET_KEY}

sys:
    user:
        password: ${USER_PASS}